#!/bin/bash

######### commands specific to this project #############
# env vars that may be used in this script:
#  $PATH
#  $TOOLWD ($(pwd))
#  $CALLERPATH
#  $PYTHONPATH
#  $TARGET

# use-cases
# 1. default: build a drawware program
# 2. build a transmogrifier
# 3. use T2T to transmogrify some text to some other text

# if you want to build a use-case 2 or use-case 3 tool, then comment out use-case 1 below and uncomment the appropriate use-case

# use-case 1 (default)
das2json ${TARGET}.drawio
python main.py "${CALLERPATH}/${TARGET}".drawio main ${TARGET}.drawio.json
rm ${TARGET}.drawio.json


# # use-case 2 (build a drawware tool that is like a compiler that transmogrifies a custom language to some existing language (say custom-to-Python)
# # 1. rebuild the drawwaretoolrifier ("compiler") every time...
# das2json ${TARGET}.drawio
# python main.py "${CALLERPATH}/${TARGET}".drawio main ${TARGET}.drawio.json | splitoutputs
# checkfailure
# mv out.py "${CALLERPATH}/${TARGET}.py"
# rm ${TARGET}.drawio.json


# # use-case 2 just use the T2T tool to convert some text to some other text ("transmogrify")
# # if you only want to use the T2T tool, then comment out the above and use the following:
# output=/dev/stdout
# ./pbp/t2t "${TARGET}" </dev/null >$output


############################



